name: Deploy Frontend with PM2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
      env:
        CI: false
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to project directory
          cd /var/www/onedukon/front
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies
          npm ci
          
          # Build the project
          npm run build
          
          # Restart PM2 process
          pm2 restart frontend || pm2 --name frontend serve --spa dist 4000
          
          # Save PM2 process list
          pm2 save
          
          # Show status
          pm2 status